# Generated by Django 5.0.7 on 2024-07-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=15)),
            ],
        ),
        migrations.RenameField(
            model_name='items',
            old_name='id',
            new_name='item_id',
        ),
    ]
