# Generated by Django 5.0.7 on 2024-07-16 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoBackend', '0002_admin_rename_id_items_item_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
